// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[Table("Course_semester")]
public partial class CourseSemester
{
    [Key]
    [Column("cycle_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string CycleId { get; set; }

    [Required]
    [Column("Semester_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string SemesterId { get; set; }

    [Required]
    [Column("Course_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string CourseId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("CourseId")]
    [InverseProperty("CourseSemesters")]
    public virtual Course Course { get; set; }

    [InverseProperty("CourseCycle")]
    public virtual ICollection<InstructorCourseSemester> InstructorCourseSemesters { get; set; } = new List<InstructorCourseSemester>();

    [InverseProperty("CourseCycle")]
    public virtual ICollection<Lecture> Lectures { get; set; } = new List<Lecture>();

    [InverseProperty("CourseCycle")]
    public virtual ICollection<Quiz> Quizzes { get; set; } = new List<Quiz>();

    [ForeignKey("SemesterId")]
    [InverseProperty("CourseSemesters")]
    public virtual Semester Semester { get; set; }

    [InverseProperty("CourseCycle")]
    public virtual ICollection<StudentEnrollment> StudentEnrollments { get; set; } = new List<StudentEnrollment>();

    [InverseProperty("CourseCycle")]
    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}