// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[Table("Course")]
public partial class Course
{
    [Key]
    [Column("course_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string CourseId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("hours")]
    public int? Hours { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("image_path")]
    [StringLength(255)]
    [Unicode(false)]
    public string ImagePath { get; set; }

    [Column("faculty_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string FacultyId { get; set; }

    [InverseProperty("Course")]
    public virtual ICollection<CourseSemester> CourseSemesters { get; set; } = new List<CourseSemester>();

    [ForeignKey("FacultyId")]
    [InverseProperty("Courses")]
    public virtual Faculty Faculty { get; set; }
}