// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[Table("Department")]
public partial class Department
{
    [Key]
    [Column("department_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string DepartmentId { get; set; }

    [Column("faculty_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string FacultyId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("FacultyId")]
    [InverseProperty("Departments")]
    public virtual Faculty Faculty { get; set; }

    [InverseProperty("Department")]
    public virtual ICollection<StudentInfo> StudentInfos { get; set; } = new List<StudentInfo>();
}