// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[PrimaryKey("CourseCycleId", "InstructorId")]
[Table("instructor_course_semester")]
public partial class InstructorCourseSemester
{
    [Key]
    [Column("instructor_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string InstructorId { get; set; }

    [Key]
    [Column("course_cycle_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string CourseCycleId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("CourseCycleId")]
    [InverseProperty("InstructorCourseSemesters")]
    public virtual CourseSemester CourseCycle { get; set; }

    [ForeignKey("InstructorId")]
    [InverseProperty("InstructorCourseSemesters")]
    public virtual User Instructor { get; set; }
}