// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[Table("Lecture")]
public partial class Lecture
{
    [Key]
    [Column("lecture_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string LectureId { get; set; }

    [Required]
    [Column("course_cycle_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string CourseCycleId { get; set; }

    [Required]
    [Column("title")]
    [StringLength(255)]
    [Unicode(false)]
    public string Title { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("type")]
    [StringLength(50)]
    public string Type { get; set; }

    [ForeignKey("CourseCycleId")]
    [InverseProperty("Lectures")]
    public virtual CourseSemester CourseCycle { get; set; }

    [InverseProperty("Lecture")]
    public virtual ICollection<LectureFile> LectureFiles { get; set; } = new List<LectureFile>();
}