// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;
[Table("news")]
public partial class News
{
    [Key]
    [Column("news_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string NewsId { get; set; }

    [Required]
    [Column("content")]
    [StringLength(255)]
    public string Content { get; set; }

    [Column("file_path")]
    [StringLength(255)]
    [Unicode(false)]
    public string FilePath { get; set; }

    [Column("faculty_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string FacultyId { get; set; }

    [Column("user_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string UserId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("FacultyId")]
    [InverseProperty("News")]
    public virtual Faculty Faculty { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("News")]
    public virtual User User { get; set; }
}