// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[Table("Question_answers")]
public partial class QuestionAnswer
{
    [Key]
    [Column("answer_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string AnswerId { get; set; }

    [Column("question_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string QuestionId { get; set; }

    [Column("text")]
    [StringLength(255)]
    [Unicode(false)]
    public string Text { get; set; }

    [Column("is_correct")]
    public bool IsCorrect { get; set; }

    [Column("answer_number")]
    public int AnswerNumber { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("QuestionAnswers")]
    public virtual Question Question { get; set; }

    [InverseProperty("QuestionAnswers")]
    public virtual ICollection<QuizAnswer> QuizAnswers { get; set; } = new List<QuizAnswer>();
}