// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[Table("Questions")]
public partial class Question
{
    [Key]
    [Column("question_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string QuestionId { get; set; }

    [Column("quiz_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string QuizId { get; set; }

    [Required]
    [Column("text")]
    [StringLength(255)]
    [Unicode(false)]
    public string Text { get; set; }

    [Required]
    [Column("type")]
    [StringLength(50)]
    [Unicode(false)]
    public string Type { get; set; }

    [Column("question_number")]
    public int QuestionNumber { get; set; }

    [Column("grade")]
    public double? Grade { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<QuestionAnswer> QuestionAnswers { get; set; } = new List<QuestionAnswer>();

    [ForeignKey("QuizId")]
    [InverseProperty("Questions")]
    public virtual Quiz Quiz { get; set; }
}