// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[Table("Quiz")]
public partial class Quiz
{
    [Key]
    [Column("quiz_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string QuizId { get; set; }

    [Required]
    [Column("title")]
    [StringLength(255)]
    [Unicode(false)]
    public string Title { get; set; }

    [Column("notes")]
    [StringLength(500)]
    [Unicode(false)]
    public string Notes { get; set; }

    [Column("start_date", TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column("end_date", TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [Column("grade")]
    public double? Grade { get; set; }

    [Column("course_cycle_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string CourseCycleId { get; set; }

    [Column("instructor_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string InstructorId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("CourseCycleId")]
    [InverseProperty("Quizzes")]
    public virtual CourseSemester CourseCycle { get; set; }

    [ForeignKey("InstructorId")]
    [InverseProperty("Quizzes")]
    public virtual User Instructor { get; set; }

    [InverseProperty("Quiz")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("Quiz")]
    public virtual ICollection<StudentQuizGrade> StudentQuizGrades { get; set; } = new List<StudentQuizGrade>();
}