// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[Table("Quiz_answers")]
public partial class QuizAnswer
{
    [Key]
    [Column("answer_ID")]
    public string AnswerId { get; set; }

    [Column("student_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string StudentId { get; set; }

    [Column("question_answers_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string QuestionAnswersId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("QuestionAnswersId")]
    [InverseProperty("QuizAnswers")]
    public virtual QuestionAnswer QuestionAnswers { get; set; }

    [ForeignKey("StudentId")]
    [InverseProperty("QuizAnswers")]
    public virtual User Student { get; set; }
}