// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[Table("Role")]
public partial class Role
{
    [Key]
    [Column("role_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string RoleId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}