// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[PrimaryKey("StudentId", "CourseCycleId")]
[Table("Student_Enrollment")]
public partial class StudentEnrollment
{
    [Key]
    [Column("student_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string StudentId { get; set; }

    [Key]
    [Column("course_cycle_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string CourseCycleId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("CourseCycleId")]
    [InverseProperty("StudentEnrollments")]
    public virtual CourseSemester CourseCycle { get; set; }

    [ForeignKey("StudentId")]
    [InverseProperty("StudentEnrollments")]
    public virtual User Student { get; set; }
}