// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[Table("Student_info")]
public partial class StudentInfo
{
    [Key]
    [Column("academic_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string AcademicId { get; set; }

    [Column("user_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string UserId { get; set; }

    [Column("department_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string DepartmentId { get; set; }

    [Column("level")]
    public int Level { get; set; }

/*    [Column("gpa")]
    public double? Gpa { get; set; }*/

    [ForeignKey("DepartmentId")]
    [InverseProperty("StudentInfos")]
    public virtual Department Department { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("StudentInfos")]
    public virtual User User { get; set; }
}