// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[Table("Task")]
public partial class Task
{
    [Key]
    [Column("task_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string TaskId { get; set; }

    [Required]
    [Column("title")]
    [StringLength(255)]
    [Unicode(false)]
    public string Title { get; set; }

    [Column("start_date", TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column("end_date", TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [Column("grade")]
    public double? Grade { get; set; }

    [Required]
    [Column("file_path")]
    [StringLength(255)]
    [Unicode(false)]
    public string FilePath { get; set; }

    [Column("course_cycle_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string CourseCycleId { get; set; }

    [Column("instructor_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string InstructorId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("CourseCycleId")]
    [InverseProperty("Tasks")]
    public virtual CourseSemester CourseCycle { get; set; }

    [ForeignKey("InstructorId")]
    [InverseProperty("Tasks")]
    public virtual User Instructor { get; set; }

    [InverseProperty("Task")]
    public virtual ICollection<TaskAnswer> TaskAnswers { get; set; } = new List<TaskAnswer>();
}