// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[Table("University")]
[Index("Name", Name = "UQ__Universi__72E12F1BD77946A1", IsUnique = true)]
public partial class University
{
    [Key]
    [Column("university_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string UniversityId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(255)]
    public string Name { get; set; }

    [Required]
    [Column("Logo_path")]
    [StringLength(255)]
    [Unicode(false)]
    public string LogoPath { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [InverseProperty("University")]
    public virtual ICollection<Faculty> Faculties { get; set; } = new List<Faculty>();
}