// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[Table("users")]
[Index("Email", Name = "UQ__users__AB6E6164094D60C7", IsUnique = true)]
[Index("Phone", Name = "UQ__users__B43B145FD7D413C2", IsUnique = true)]
public partial class User
{
    [Key]
    [Column("user_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string UserId { get; set; }

    [Required]
    [Column("full_name")]
    [StringLength(255)]
    public string FullName { get; set; }

    [Required]
    [Column("email")]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [Column("password")]
    [StringLength(255)]
    [Unicode(false)]
    public string Password { get; set; }

    [Column("phone")]
    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Column("image_path")]
    [StringLength(255)]
    [Unicode(false)]
    public string ImagePath { get; set; }

    [Column("Faculty_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string FacultyId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("status")]
    [StringLength(50)]
    [Unicode(false)]
    public string Status { get; set; }

    [ForeignKey("FacultyId")]
    [InverseProperty("Users")]
    public virtual Faculty Faculty { get; set; }

    [InverseProperty("Instructor")]
    public virtual ICollection<InstructorCourseSemester> InstructorCourseSemesters { get; set; } = new List<InstructorCourseSemester>();

    [InverseProperty("User")]
    public virtual ICollection<News> News { get; set; } = new List<News>();

    [InverseProperty("Student")]
    public virtual ICollection<QuizAnswer> QuizAnswers { get; set; } = new List<QuizAnswer>();

    [InverseProperty("Instructor")]
    public virtual ICollection<Quiz> Quizzes { get; set; } = new List<Quiz>();

    [InverseProperty("Student")]
    public virtual ICollection<StudentEnrollment> StudentEnrollments { get; set; } = new List<StudentEnrollment>();

    [InverseProperty("User")]
    public virtual ICollection<StudentInfo> StudentInfos { get; set; } = new List<StudentInfo>();

    [InverseProperty("Student")]
    public virtual ICollection<StudentQuizGrade> StudentQuizGrades { get; set; } = new List<StudentQuizGrade>();

    [InverseProperty("Student")]
    public virtual ICollection<TaskAnswer> TaskAnswers { get; set; } = new List<TaskAnswer>();

    [InverseProperty("Instructor")]
    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();

    [InverseProperty("User")]
    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}