// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CRUDApi.Models;

[PrimaryKey("RoleId", "UserId")]
[Table("User_role")]
public partial class UserRole
{
    [Key]
    [Column("role_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string RoleId { get; set; }

    [Key]
    [Column("user_ID")]
    [StringLength(50)]
    [Unicode(false)]
    public string UserId { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("UserRoles")]
    public virtual Role Role { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserRoles")]
    public virtual User User { get; set; }
}